### PR TITLE
Add clean fix for cancelation on 3.9+.

### PR DESCRIPTION
**Pull request by Dreamsorcerer**

### CODE REVIEW

**Comment by webknjaz** [comment]
@Dreamsorcerer do you want to resurrect this effort?

**Comment by webknjaz** [comment]
Is it related to #295?

**Comment by Dreamsorcerer** [comment]
> @Dreamsorcerer do you want to resurrect this effort?

I will return to this in some form, and verify if the problem is actually fixed in asyncio.timeout() or not. But, this library itself should probably be deprecated (and archived once asyncio.timeout() is available in all supported versions of Python).

> Is it related to #295?

Yes, I'm pretty sure that PR is incorrect, as explained in my comments.

**Comment by asvetlov** [comment]
Version 5.0+ wiorks exactly as `asyncio` built-in does, nothing to do here.

**Pull request closed without merging**
