### PR TITLE
Add support for Python 3.12-3.13 and drop EOL 3.7

### PR DESCRIPTION
**Pull request by hugovk**
## What do these changes do?

The [Python 3.12 release candidate is out!](https://discuss.python.org/t/python-3-12-0-release-candidate-1-released/31137?u=hugovk) :rocket:

> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.

See also https://dev.to/hugovk/help-test-python-312-beta-1508/

Also drop EOL Python 3.7.

## Are there changes in behavior for the user?

No.

## Related issue number

n/a

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by hugovk** [comment]
Updated to to add support for the Python 3.13 release candidate! :rocket:

The Release Manager has issued a [call to action](https://discuss.python.org/t/python-3-13-0-release-candidate-1-released/59703?u=hugovk]):

> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.13 compatibilities during this phase, and where necessary publish Python 3.13 wheels on PyPI to be ready for the final release of 3.13.0. Any binary wheels built against Python 3.13.0rc1 **will work** with future versions of Python 3.13. As always, report any issues to [the Python bug tracker](https://github.com/python/cpython/issues).

Also update Twine to fix the CI.

PS I usually close PRs when they gets to one year old, this is now 11 months old. Please let me know if you need more time or there's something else to do here. Thanks!

**Comment by Hedda** [comment]
Any updates on this? Please also see this issue:

* https://github.com/aio-libs/async-timeout/issues/413

**Comment by hugovk** [comment]
Closing this year old PR, but happy to re-open if there's interest.

**Comment by Hedda** [comment]
> Closing this year old PR, but happy to re-open if there's interest.

There is interest but someone with commit permissions/rights has to review and merge if acceptable to them, or create a fork? 😕 

@Dreamsorcerer @asvetlov @webknjaz @hugovk

**Comment by Dreamsorcerer** [comment]
I've unsubscribed from the repo as I think we'll just archive this project soon, as the code has been upstreamed to asyncio.timeout() and I see little reason to continue it's development.

Once Python 3.10 is no longer supported, we'll probably kill it officially, until then it's basically hanging around in case of security issues etc. that could need fixing. We've already dropped it in all our other projects, which you can do too using the same approach:
https://github.com/aio-libs/aiohttp/blob/5c0b8e4a7897f48063f684ac16e7dd18f6218274/aiohttp/helpers.py#L59-L62
https://github.com/aio-libs/aiohttp/blob/master/setup.cfg#L53

**Comment by Dreamsorcerer** [comment]
Have updated the README to make this clear and provide those migration instructions.

**Pull request closed without merging**
